dbt_fundamentals:
  outputs:
    dev:
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /home/lvmartins/dbt-sa-lvmartins.json
      location: EU
      method: service-account
      priority: interactive
      project: dbt-fundamentals-lvmartins
      schema: dbt_fundamentals
      threads: 1
      type: bigquery
  target: dev

